#!/bin/bash
# Auto-generated by install.sh — do not edit by hand. Chrome's
# hardened-runtime sandbox refuses to honor #!/usr/bin/env shebangs
# when spawning Native Messaging hosts on macOS, so this wrapper
# execs node with an absolute path resolved at install time.
exec "/Users/geoffreydudgeon/.nvm/versions/node/v18.17.0/bin/node" "$(dirname "$0")/duo-helper.js"
