#!/bin/bash
# Duo Phase 0 — Native Messaging registry installer (macOS).
#
# Usage: ./install.sh <extension-id>
#
# extension-id is the Chrome ID shown on chrome://extensions/ after
# loading phase0/extension/ as an unpacked extension. Looks like
# "abcdefghijklmnopqrstuvwxyzabcdef" (32 lowercase letters).

set -e

if [ $# -lt 1 ]; then
  echo "usage: $0 <extension-id>"
  echo
  echo "Get the extension-id by:"
  echo "  1. open chrome://extensions/"
  echo "  2. flip 'Developer mode' on"
  echo "  3. 'Load unpacked' → select phase0/extension/"
  echo "  4. copy the ID shown under the extension card"
  exit 1
fi

EXTENSION_ID="$1"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# macOS gotcha #1: Chrome's NM-host spawn doesn't honor shebangs reliably
# under hardened-runtime sandboxing. The launcher wrapper is what Chrome
# actually executes; it execs node with an explicit absolute path. We
# write the launcher fresh on each install so the node path matches the
# user's actual machine (nvm, brew, system, etc.).
LAUNCHER_PATH="$SCRIPT_DIR/duo-helper-launcher.sh"
HELPER_PATH="$SCRIPT_DIR/duo-helper.js"

NODE_BIN="$(command -v node || true)"
if [ -z "$NODE_BIN" ]; then
  echo "error: node not found on PATH. Install Node.js first." >&2
  exit 1
fi

cat > "$LAUNCHER_PATH" <<LAUNCHER_EOF
#!/bin/bash
# Auto-generated by install.sh — do not edit by hand. Chrome's
# hardened-runtime sandbox refuses to honor #!/usr/bin/env shebangs
# when spawning Native Messaging hosts on macOS, so this wrapper
# execs node with an absolute path resolved at install time.
exec "$NODE_BIN" "\$(dirname "\$0")/duo-helper.js"
LAUNCHER_EOF

# macOS gotcha #2: files created by certain processes get a
# `com.apple.provenance` xattr (Sequoia file-tracking). Chrome's
# spawn refuses to exec those silently. Strip it.
xattr -d com.apple.provenance "$LAUNCHER_PATH" 2>/dev/null || true
xattr -d com.apple.provenance "$HELPER_PATH" 2>/dev/null || true

NM_DIR="$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts"
NM_PATH="$NM_DIR/com.duo.phase0.json"

mkdir -p "$NM_DIR"
chmod +x "$LAUNCHER_PATH" "$HELPER_PATH"

cat > "$NM_PATH" <<EOF
{
  "name": "com.duo.phase0",
  "description": "Duo Phase 0 — keep-alive probe helper",
  "path": "$LAUNCHER_PATH",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://$EXTENSION_ID/"
  ]
}
EOF

echo "✓ Native Messaging manifest installed"
echo "  manifest: $NM_PATH"
echo "  launcher: $LAUNCHER_PATH"
echo "  helper:   $HELPER_PATH"
echo "  origin:   chrome-extension://$EXTENSION_ID/"
echo
echo "Next:"
echo "  1. open the extension popup, click 'Send ping to helper'"
echo "  2. expected: ✓ pong in &lt;10ms"
echo "  3. tail the helper log to watch keep-alive ticks:"
echo "     tail -f \"\$HOME/.claude/duo/phase0-helper.log\""
echo
echo "To uninstall: rm \"$NM_PATH\""
