#!/bin/bash
# Duo Phase 0 — Native Messaging registry installer (macOS).
#
# Usage: ./install.sh <extension-id>
#
# extension-id is the Chrome ID shown on chrome://extensions/ after
# loading phase0/extension/ as an unpacked extension. Looks like
# "abcdefghijklmnopqrstuvwxyzabcdef" (32 lowercase letters).

set -e

if [ $# -lt 1 ]; then
  echo "usage: $0 <extension-id>"
  echo
  echo "Get the extension-id by:"
  echo "  1. open chrome://extensions/"
  echo "  2. flip 'Developer mode' on"
  echo "  3. 'Load unpacked' → select phase0/extension/"
  echo "  4. copy the ID shown under the extension card"
  exit 1
fi

EXTENSION_ID="$1"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# macOS Sequoia gotcha: Chrome's NM-host spawn cannot reach paths
# under ~/Documents because of the new privacy gate on Documents/
# Downloads/Desktop. Symptom: connectNative succeeds but the helper
# never boots (no log entry, port disconnects silently). Empirically
# verified 2026-04-30 — see phase0/README.md § Known gotchas.
#
# We side-step the gate by copying the helper + launcher into
# ~/Library/Application Support/Duo/ which is in user space but
# outside the gated directories. This also makes installs robust
# across worktrees: the active worktree's helper code is what gets
# deployed, regardless of where the worktree lives on disk.
INSTALL_DIR="$HOME/Library/Application Support/Duo"
LAUNCHER_PATH="$INSTALL_DIR/duo-helper-launcher.sh"
HELPER_PATH="$INSTALL_DIR/duo-helper.js"
HELPER_SOURCE="$SCRIPT_DIR/duo-helper.js"

if [ ! -f "$HELPER_SOURCE" ]; then
  echo "error: helper source not found at $HELPER_SOURCE" >&2
  exit 1
fi

NODE_BIN="$(command -v node || true)"
if [ -z "$NODE_BIN" ]; then
  echo "error: node not found on PATH. Install Node.js first." >&2
  exit 1
fi

# node-pty is a native dependency. The helper at the install
# location is no longer next to the project's node_modules, so it
# can't find node-pty via the standard walk-up. Resolve at install
# time and bake into NODE_PATH on the launcher.
DIR="$SCRIPT_DIR"
NODE_MODULES_DIR=""
while [ "$DIR" != "/" ]; do
  if [ -d "$DIR/node_modules/node-pty" ]; then
    NODE_MODULES_DIR="$DIR/node_modules"
    break
  fi
  DIR="$(dirname "$DIR")"
done
if [ -z "$NODE_MODULES_DIR" ]; then
  echo "error: cannot find node_modules/node-pty by walking up from $SCRIPT_DIR" >&2
  echo "       did you run 'npm install' in the project root?" >&2
  exit 1
fi

mkdir -p "$INSTALL_DIR"

# Copy helper source into the install dir each run so worktree edits
# reach Chrome the next time the SW respawns the host.
cp "$HELPER_SOURCE" "$HELPER_PATH"

cat > "$LAUNCHER_PATH" <<LAUNCHER_EOF
#!/bin/bash
# Auto-generated by phase0/helper/install.sh — do not edit by hand.
# Lives at ~/Library/Application Support/Duo/ to side-step macOS
# Sequoia's privacy gate on ~/Documents (Chrome NM-host spawn fails
# silently inside the gate). NODE_PATH is baked at install time so
# node-pty resolves without the helper being inside the project tree.
export NODE_PATH="$NODE_MODULES_DIR"
exec "$NODE_BIN" "\$(dirname "\$0")/duo-helper.js"
LAUNCHER_EOF

# Best-effort xattr strip. macOS Sequoia auto-tags files with
# com.apple.provenance regardless of where they land; the tag does
# not appear to block Chrome NM-host spawn outside ~/Documents, but
# we strip anyway to keep the surface clean.
xattr -d com.apple.provenance "$LAUNCHER_PATH" 2>/dev/null || true
xattr -d com.apple.provenance "$HELPER_PATH"   2>/dev/null || true

chmod +x "$LAUNCHER_PATH" "$HELPER_PATH"

NM_DIR="$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts"
NM_PATH="$NM_DIR/com.duo.phase0.json"

mkdir -p "$NM_DIR"

cat > "$NM_PATH" <<EOF
{
  "name": "com.duo.phase0",
  "description": "Duo Phase 0 — keep-alive probe helper",
  "path": "$LAUNCHER_PATH",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://$EXTENSION_ID/"
  ]
}
EOF

echo "✓ Native Messaging manifest installed"
echo "  manifest:    $NM_PATH"
echo "  launcher:    $LAUNCHER_PATH"
echo "  helper:      $HELPER_PATH"
echo "  node-pty in: $NODE_MODULES_DIR"
echo "  origin:      chrome-extension://$EXTENSION_ID/"
echo
echo "Next:"
echo "  1. reload the extension at chrome://extensions/"
echo "  2. open the side panel — terminal should show a prompt"
echo "  3. tail the helper log to watch keep-alive ticks:"
echo "     tail -f \"\$HOME/.claude/duo/phase0-helper.log\""
echo
echo "If you switch worktrees: re-run this script from the new worktree"
echo "to redeploy the helper code from the worktree you're now editing."
echo
echo "To uninstall: rm \"$NM_PATH\" \"$LAUNCHER_PATH\" \"$HELPER_PATH\""
