// ENH-177 — encodeProjectDir tests against real Claude Code directory
// names observed on disk 2026-05-23.
// ENH-183 C4 — cleanAndTruncate + readBannerTitle + readMessageCount.
// ENH-212 — Home data primitives: listTopLevelSessions +
// readSessionTailMeta + readSessionHeadMeta.

import { describe, expect, it, beforeEach, afterEach, vi } from 'vitest'
import { promises as fs } from 'fs'
import path from 'path'
import os from 'os'
import {
  buildResumeCommand,
  encodeProjectDir,
  cleanAndTruncate,
  readBannerTitle,
  readMessageCount,
  listTopLevelSessions,
  readSessionTailMeta,
  readSessionHeadMeta,
} from './claude-session-tracker'

describe('buildResumeCommand — ENH-212 fork vs resume', () => {
  const uuid = '75b057bd-07fd-4a08-a633-671e94587dd5'

  it('plain resume continues the session in place (no --fork-session)', () => {
    expect(buildResumeCommand(uuid)).toBe(`claude --resume ${uuid}\n`)
    expect(buildResumeCommand(uuid, { fork: false })).toBe(`claude --resume ${uuid}\n`)
  })

  it('fork appends --fork-session so a still-live session is branched, not clobbered', () => {
    // The bug the owner caught on the v0.10.3 walk: the Fork button ran a plain
    // `--resume`, attaching a second writer to the running session's JSONL.
    expect(buildResumeCommand(uuid, { fork: true })).toBe(
      `claude --resume ${uuid} --fork-session\n`
    )
  })

  it('always ends with a newline so the spawned shell auto-runs it', () => {
    expect(buildResumeCommand(uuid).endsWith('\n')).toBe(true)
    expect(buildResumeCommand(uuid, { fork: true }).endsWith('\n')).toBe(true)
  })
})

describe('encodeProjectDir — ENH-177', () => {
  it('encodes a simple home path', () => {
    expect(encodeProjectDir('/Users/geoffreydudgeon')).toBe('-Users-geoffreydudgeon')
  })

  it('encodes Documents/GitHub/duo (the canonical repo path)', () => {
    expect(encodeProjectDir('/Users/geoffreydudgeon/Documents/GitHub/duo'))
      .toBe('-Users-geoffreydudgeon-Documents-GitHub-duo')
  })

  it('encodes ~/.claude/skills/duo (dot → dash)', () => {
    expect(encodeProjectDir('/Users/geoffreydudgeon/.claude/skills/duo'))
      .toBe('-Users-geoffreydudgeon--claude-skills-duo')
  })

  it('encodes a worktree path with .claude embedded', () => {
    expect(encodeProjectDir('/Users/geoffreydudgeon/Documents/GitHub/duo/.claude/worktrees/amazing-hertz-9f5e6c'))
      .toBe('-Users-geoffreydudgeon-Documents-GitHub-duo--claude-worktrees-amazing-hertz-9f5e6c')
  })

  it('preserves dashes inside path segments', () => {
    expect(encodeProjectDir('/foo/bar-baz/qux'))
      .toBe('-foo-bar-baz-qux')
  })

  it('handles multi-segment dotfile paths', () => {
    expect(encodeProjectDir('/a/.b/.c/d'))
      .toBe('-a--b--c-d')
  })

  it('resolves symlinks before encoding (BUG-158)', () => {
    // macOS: /tmp is a symlink to /private/tmp. Claude resolves
    // symlinks before writing to ~/.claude/projects/, so a session
    // started at /tmp/X is written to -private-tmp-X, not -tmp-X.
    // Skip on non-darwin where /tmp may not have this symlink.
    if (process.platform !== 'darwin') return
    expect(encodeProjectDir('/tmp')).toBe('-private-tmp')
  })

  it('falls back to literal encoding when path does not exist (BUG-158)', () => {
    // realpath throws ENOENT for non-existent paths — encoder should
    // catch + fall back to literal encoding (same behavior as before
    // the BUG-158 fix for non-existent paths).
    expect(encodeProjectDir('/this/path/does/not/exist/abc123'))
      .toBe('-this-path-does-not-exist-abc123')
  })
})

describe('cleanAndTruncate — ENH-183 C4', () => {
  it('returns empty string for empty input', () => {
    expect(cleanAndTruncate('')).toBe('')
    expect(cleanAndTruncate('   ')).toBe('')
  })

  it('strips ide_opened_file sentinel wrappers', () => {
    const raw = '<ide_opened_file>The user opened the file /tmp/foo.ts in the IDE. This may or may not be related to the current task.</ide_opened_file>fix the typo'
    expect(cleanAndTruncate(raw)).toBe('Fix the typo')
  })

  it('strips orphan ide_opened_file open/close tags (no body to keep)', () => {
    expect(cleanAndTruncate('<ide_opened_file>fix it</ide_opened_file>')).toBe('')
    // Trailing user text after the wrapper survives.
    expect(cleanAndTruncate('<ide_opened_file>noise</ide_opened_file>fix it'))
      .toBe('Fix it')
    // Orphan unmatched closing tag is still stripped.
    expect(cleanAndTruncate('please </ide_opened_file>fix it'))
      .toBe('Fix it')
  })

  it('strips local-command / slash-command / system-reminder wrappers (round-2)', () => {
    // A session whose opener is pure machinery → empty (forward scan falls
    // through to the next real message).
    expect(cleanAndTruncate('<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond…</local-command-caveat>')).toBe('')
    expect(cleanAndTruncate('<command-name>/model</command-name><command-message>model</command-message><command-args>opus</command-args>')).toBe('')
    expect(cleanAndTruncate('<system-reminder>Some injected note.</system-reminder>')).toBe('')
    // Real prose after a wrapper survives.
    expect(cleanAndTruncate('<local-command-stdout>ran ok</local-command-stdout>fix the parser')).toBe('Fix the parser')
  })

  it('drops conversational prefixes case-insensitively', () => {
    expect(cleanAndTruncate('please fix the bug')).toBe('Fix the bug')
    expect(cleanAndTruncate('Could you add a test?')).toBe('Add a test?')
    expect(cleanAndTruncate('can you check this')).toBe('Check this')
    expect(cleanAndTruncate('Hey, what is wrong here')).toBe('What is wrong here')
  })

  it('collapses multi-line input to a single line', () => {
    expect(cleanAndTruncate('refactor\n\n  the\tparser')).toBe('Refactor the parser')
  })

  it('truncates at 60 chars on a word boundary with ellipsis', () => {
    const raw = 'add a feature flag to gate the new browser blocklist behavior for enterprise users only please'
    const out = cleanAndTruncate(raw)
    expect(out.length).toBeLessThanOrEqual(61) // +1 for the …
    expect(out.endsWith('…')).toBe(true)
    expect(out).not.toContain('  ')
  })

  it('handles very-long single-token strings with hard cut + ellipsis', () => {
    const raw = 'a'.repeat(120)
    const out = cleanAndTruncate(raw)
    expect(out.length).toBeLessThanOrEqual(61)
    expect(out.endsWith('…')).toBe(true)
  })

  it('returns text unchanged if already short + clean', () => {
    expect(cleanAndTruncate('Refactor X')).toBe('Refactor X')
  })
})

// Integration tests for readBannerTitle / readMessageCount.
// These write real JSONL fixtures into a sandboxed projects dir, point
// the SUT at it via cwd-encoding, and confirm the read ladder fires
// each rung correctly. Cleanup deletes the entire sandbox dir.
describe('readBannerTitle + readMessageCount — ENH-183 C4 integration', () => {
  let sandbox: string
  let cwd: string

  // Stub the Claude projects directory inside a temp dir. We achieve
  // this by overriding os.homedir for the encoder — but encodeProjectDir
  // uses absolute paths, so the simpler trick is to set up the real
  // path under the real ~/.claude/projects/ with a unique fake cwd we
  // know won't collide.
  beforeEach(async () => {
    const uniq = `enh-183-c4-test-${process.pid}-${Date.now()}`
    cwd = `/tmp/${uniq}`
    const encoded = encodeProjectDir(cwd)
    sandbox = path.join(os.homedir(), '.claude', 'projects', encoded)
    await fs.mkdir(sandbox, { recursive: true })
  })

  afterEach(async () => {
    await fs.rm(sandbox, { recursive: true, force: true })
  })

  async function writeJsonl(uuid: string, lines: object[]): Promise<void> {
    const content = lines.map((l) => JSON.stringify(l)).join('\n') + '\n'
    await fs.writeFile(path.join(sandbox, `${uuid}.jsonl`), content, 'utf8')
  }

  it('rung 1 — picks the latest custom-title entry', async () => {
    const uuid = '11111111-1111-1111-1111-111111111111'
    await writeJsonl(uuid, [
      { type: 'user', message: { content: 'hello there' } },
      { type: 'custom-title', customTitle: 'first rename', sessionId: uuid },
      { type: 'ai-title', aiTitle: 'haiku summary', sessionId: uuid },
      { type: 'custom-title', customTitle: 'second rename', sessionId: uuid },
    ])
    const r = await readBannerTitle(uuid, cwd)
    expect(r).toEqual({ title: 'second rename', source: 'customTitle' })
  })

  it('rung 2 — falls back to ai-title when no custom-title exists', async () => {
    const uuid = '22222222-2222-2222-2222-222222222222'
    await writeJsonl(uuid, [
      { type: 'user', message: { content: 'do the thing' } },
      { type: 'ai-title', aiTitle: 'doing the thing', sessionId: uuid },
    ])
    const r = await readBannerTitle(uuid, cwd)
    expect(r).toEqual({ title: 'doing the thing', source: 'aiTitle' })
  })

  it('rung 3 — falls back to cleaned first user message', async () => {
    const uuid = '33333333-3333-3333-3333-333333333333'
    await writeJsonl(uuid, [
      { type: 'system', content: 'system bootstrap' },
      { type: 'user', message: { content: 'please fix the bug in the parser' } },
      { type: 'assistant', content: 'sure' },
    ])
    const r = await readBannerTitle(uuid, cwd)
    expect(r).toEqual({ title: 'Fix the bug in the parser', source: 'jsonl-firstmsg' })
  })

  it('rung 3 — handles array-shaped user content blocks', async () => {
    const uuid = '44444444-4444-4444-4444-444444444444'
    await writeJsonl(uuid, [
      { type: 'user', message: { content: [{ type: 'text', text: 'add a regression test' }] } },
    ])
    const r = await readBannerTitle(uuid, cwd)
    expect(r).toEqual({ title: 'Add a regression test', source: 'jsonl-firstmsg' })
  })

  it('rung 4 — falls back to short UUID when JSONL is empty', async () => {
    const uuid = '55555555-5555-5555-5555-555555555555'
    await writeJsonl(uuid, [])
    const r = await readBannerTitle(uuid, cwd)
    expect(r).toEqual({ title: '55555555', source: 'uuid' })
  })

  it('rung 4 — falls back to short UUID when JSONL is missing', async () => {
    const uuid = '66666666-6666-6666-6666-666666666666'
    // Don't write the file.
    const r = await readBannerTitle(uuid, cwd)
    expect(r).toEqual({ title: '66666666', source: 'uuid' })
  })

  it('readMessageCount — counts type:user entries only', async () => {
    const uuid = '77777777-7777-7777-7777-777777777777'
    await writeJsonl(uuid, [
      { type: 'user', message: { content: 'one' } },
      { type: 'assistant', content: 'reply' },
      { type: 'user', message: { content: 'two' } },
      { type: 'system', content: 'sys' },
      { type: 'user', message: { content: 'three' } },
      { type: 'custom-title', customTitle: 'x' },
    ])
    expect(await readMessageCount(uuid, cwd)).toBe(3)
  })

  it('readMessageCount — returns 0 when JSONL is missing', async () => {
    const uuid = '88888888-8888-8888-8888-888888888888'
    expect(await readMessageCount(uuid, cwd)).toBe(0)
  })
})

// ---------------------------------------------------------------------------
// ENH-212 — Home data primitives. Fixtures live in a plain temp dir
// (these functions take file/dir paths directly — no cwd encoding).
// Entry shapes mirror real ~/.claude/projects/ JSONLs inspected
// 2026-06-12: assistant content is a block array (thinking/text),
// entries carry isSidechain/gitBranch/sessionId/timestamp/cwd, and
// last-prompt records optionally carry a lastPrompt text field.
// ---------------------------------------------------------------------------

describe('ENH-212 Home data primitives', () => {
  let dir: string

  beforeEach(async () => {
    dir = await fs.mkdtemp(path.join(os.tmpdir(), 'enh-212-tracker-test-'))
  })

  afterEach(async () => {
    vi.restoreAllMocks()
    await fs.rm(dir, { recursive: true, force: true })
  })

  function jsonl(lines: object[]): string {
    return lines.map((l) => JSON.stringify(l)).join('\n') + '\n'
  }

  function assistantEntry(text: string, extra: object = {}): object {
    return {
      parentUuid: 'p',
      isSidechain: false,
      type: 'assistant',
      message: {
        role: 'assistant',
        content: [
          { type: 'thinking', thinking: 'hmm' },
          { type: 'text', text },
        ],
      },
      uuid: 'u',
      timestamp: '2026-06-10T01:14:32.395Z',
      cwd: '/Users/x/proj',
      sessionId: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
      gitBranch: 'main',
      ...extra,
    }
  }

  function userEntry(text: string, extra: object = {}): object {
    return {
      parentUuid: null,
      isSidechain: false,
      type: 'user',
      message: { role: 'user', content: text },
      uuid: 'u2',
      timestamp: '2026-06-10T01:00:00.000Z',
      cwd: '/Users/x/proj',
      sessionId: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
      gitBranch: 'main',
      ...extra,
    }
  }

  describe('listTopLevelSessions', () => {
    it('returns id + mtime + size for top-level .jsonl files only', async () => {
      const uuidA = '11111111-1111-1111-1111-111111111111'
      const uuidB = '22222222-2222-2222-2222-222222222222'
      await fs.writeFile(path.join(dir, `${uuidA}.jsonl`), jsonl([userEntry('a')]))
      await fs.writeFile(path.join(dir, `${uuidB}.jsonl`), jsonl([userEntry('bb')]))
      // Non-jsonl noise + a bare .jsonl name are skipped.
      await fs.writeFile(path.join(dir, 'sessions-index.json'), '{}')
      await fs.writeFile(path.join(dir, '.jsonl'), '')

      const out = await listTopLevelSessions(dir)
      expect(out.map((s) => s.id).sort()).toEqual([uuidA, uuidB])
      for (const s of out) {
        expect(s.mtimeMs).toBeGreaterThan(0)
        expect(s.sizeBytes).toBeGreaterThan(0)
      }
    })

    it('excludes subagent transcripts under <uuid>/subagents/** (incl. nested workflows)', async () => {
      const uuid = '33333333-3333-3333-3333-333333333333'
      await fs.writeFile(path.join(dir, `${uuid}.jsonl`), jsonl([userEntry('top')]))
      // Real layout observed live: <uuid>/subagents/agent-*.jsonl and
      // <uuid>/subagents/workflows/<wf>/agent-*.jsonl.
      const sub = path.join(dir, uuid, 'subagents')
      await fs.mkdir(path.join(sub, 'workflows', 'wf_x'), { recursive: true })
      await fs.writeFile(path.join(sub, 'agent-abc123.jsonl'), jsonl([userEntry('sub')]))
      await fs.writeFile(path.join(sub, 'workflows', 'wf_x', 'agent-def456.jsonl'), jsonl([userEntry('wf')]))

      const out = await listTopLevelSessions(dir)
      expect(out.map((s) => s.id)).toEqual([uuid])
    })

    it('never throws — missing dir returns []', async () => {
      expect(await listTopLevelSessions(path.join(dir, 'does-not-exist'))).toEqual([])
    })
  })

  describe('readSessionTailMeta', () => {
    it('extracts snippet from the last assistant entry + gitBranch/sessionId/timestamp', async () => {
      const file = path.join(dir, 'a.jsonl')
      await fs.writeFile(file, jsonl([
        userEntry('start'),
        assistantEntry('earlier reply'),
        assistantEntry('the final word', { gitBranch: 'feature/x', timestamp: '2026-06-11T08:00:00.000Z' }),
        { type: 'last-prompt', leafUuid: 'l', sessionId: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' },
      ]))
      const meta = await readSessionTailMeta(file)
      expect(meta.snippet).toBe('the final word')
      expect(meta.gitBranch).toBe('feature/x')
      expect(meta.sessionId).toBe('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa')
      expect(meta.timestamp).toBe(Date.parse('2026-06-11T08:00:00.000Z'))
    })

    it('skips isSidechain assistant entries', async () => {
      const file = path.join(dir, 'b.jsonl')
      await fs.writeFile(file, jsonl([
        assistantEntry('main-thread reply'),
        assistantEntry('sidechain noise', { isSidechain: true }),
      ]))
      const meta = await readSessionTailMeta(file)
      expect(meta.snippet).toBe('main-thread reply')
    })

    it('falls back to a last-prompt record when no assistant text exists', async () => {
      const file = path.join(dir, 'c.jsonl')
      await fs.writeFile(file, jsonl([
        userEntry('typed something'),
        { type: 'last-prompt', lastPrompt: 'I want to talk through a new feature', leafUuid: 'l', sessionId: 's' },
      ]))
      const meta = await readSessionTailMeta(file)
      expect(meta.snippet).toBe('I want to talk through a new feature')
    })

    it('grows the window exponentially past a ~400KB single line', async () => {
      // One assistant entry whose JSON line is ~400KB (giant thinking
      // block). 64KB/256KB tail windows land mid-line and trim to
      // ZERO complete lines; the 1MB rung covers the line start.
      const file = path.join(dir, 'giant-line.jsonl')
      const entry = {
        ...assistantEntry('found after retry'),
        message: {
          role: 'assistant',
          content: [
            { type: 'thinking', thinking: 'x'.repeat(400 * 1024) },
            { type: 'text', text: 'found after retry' },
          ],
        },
      }
      await fs.writeFile(file, jsonl([entry]))
      const meta = await readSessionTailMeta(file)
      expect(meta.snippet).toBe('found after retry')
    })

    it('bounds bytes read on a multi-MB file (never slurps)', async () => {
      // ~6MB of filler lines with the assistant snippet at the very
      // end: the first 64KB tail window must satisfy the read. Bytes
      // are counted by wrapping FileHandle.read via an fs.open spy.
      const file = path.join(dir, 'giant-file.jsonl')
      const filler = jsonl(Array.from({ length: 6000 }, (_, i) => userEntry(`filler ${i} ${'y'.repeat(1024)}`)))
      const tail = jsonl([assistantEntry('needle at the end')])
      await fs.writeFile(file, filler + tail)
      const { size } = await fs.stat(file)
      expect(size).toBeGreaterThan(5 * 1024 * 1024)

      let bytesRead = 0
      const realOpen = fs.open.bind(fs)
      vi.spyOn(fs, 'open').mockImplementation(async (...args: Parameters<typeof fs.open>) => {
        const handle = await realOpen(...args)
        const realRead = handle.read.bind(handle)
        vi.spyOn(handle, 'read').mockImplementation(async (...readArgs: unknown[]) => {
          const res = await (realRead as (...a: unknown[]) => Promise<{ bytesRead: number }>)(...readArgs)
          bytesRead += res.bytesRead
          return res as never
        })
        return handle
      })

      const meta = await readSessionTailMeta(file)
      expect(meta.snippet).toBe('needle at the end')
      // One 64KB window — nowhere near the 6MB file size.
      expect(bytesRead).toBeLessThanOrEqual(64 * 1024)
      expect(bytesRead).toBeGreaterThan(0)
    })

    it('trims the leading partial line after a seek', async () => {
      // A ~70KB line followed by the real tail entries: the 64KB
      // window starts mid-line — the fragment must be discarded, not
      // parsed, and the trailing complete lines still win.
      const file = path.join(dir, 'partial-trim.jsonl')
      await fs.writeFile(file, jsonl([
        userEntry('z'.repeat(70 * 1024)),
        assistantEntry('after the fragment'),
      ]))
      const meta = await readSessionTailMeta(file)
      expect(meta.snippet).toBe('after the fragment')
    })

    it('never throws — corrupt lines degrade to nulls', async () => {
      const file = path.join(dir, 'corrupt.jsonl')
      await fs.writeFile(file, 'not json at all\n{"broken": \ntrailing garbage')
      const meta = await readSessionTailMeta(file)
      expect(meta).toEqual({ snippet: null, gitBranch: null, sessionId: null, timestamp: null })
    })

    it('never throws — missing file returns nulls', async () => {
      const meta = await readSessionTailMeta(path.join(dir, 'nope.jsonl'))
      expect(meta).toEqual({ snippet: null, gitBranch: null, sessionId: null, timestamp: null })
    })

    it('handles an empty file', async () => {
      const file = path.join(dir, 'empty.jsonl')
      await fs.writeFile(file, '')
      const meta = await readSessionTailMeta(file)
      expect(meta).toEqual({ snippet: null, gitBranch: null, sessionId: null, timestamp: null })
    })
  })

  describe('readSessionHeadMeta', () => {
    it('reads cwd from the first user entry past cwd-less head records', async () => {
      // Real files open with queue-operation / last-prompt records
      // that carry NO cwd — the first user entry is the evidence.
      const file = path.join(dir, 'head.jsonl')
      await fs.writeFile(file, jsonl([
        { type: 'queue-operation', operation: 'enqueue', timestamp: '2026-06-08T17:10:59.534Z', sessionId: 's' },
        { type: 'last-prompt', leafUuid: 'l', sessionId: 's' },
        userEntry('first prompt', { cwd: '/Users/x/proj/sub/dir' }),
      ]))
      const meta = await readSessionHeadMeta(file)
      expect(meta.cwd).toBe('/Users/x/proj/sub/dir')
    })

    it('applies the title ladder over the head window', async () => {
      const file = path.join(dir, 'head-title.jsonl')
      await fs.writeFile(file, jsonl([
        userEntry('please fix the bug in the parser'),
        { type: 'custom-title', customTitle: 'parser fix', sessionId: 's' },
      ]))
      const meta = await readSessionHeadMeta(file)
      expect(meta.title).toBe('parser fix')
      expect(meta.titleSource).toBe('customTitle')
    })

    it('falls back to the cleaned first user message for the title', async () => {
      const file = path.join(dir, 'head-firstmsg.jsonl')
      await fs.writeFile(file, jsonl([userEntry('please fix the bug in the parser')]))
      const meta = await readSessionHeadMeta(file)
      expect(meta.title).toBe('Fix the bug in the parser')
      expect(meta.titleSource).toBe('jsonl-firstmsg')
    })

    it('uses a /rename custom-title that sits PAST the head window (tail scan)', async () => {
      // round-2 feedback: `/rename` appends a custom-title entry wherever the
      // user runs it — typically deep in the session, beyond the 16KB head.
      // The first user message is in the head; a huge filler pushes the
      // custom-title past 16KB so only the tail scan can find it.
      const file = path.join(dir, 'head-rename-late.jsonl')
      await fs.writeFile(file, jsonl([
        userEntry('please fix the bug in the parser', { cwd: '/Users/x/proj' }),
        assistantEntry('z'.repeat(40 * 1024)),
        { type: 'custom-title', customTitle: 'Parser rewrite', sessionId: 's' },
      ]))
      const meta = await readSessionHeadMeta(file)
      expect(meta.cwd).toBe('/Users/x/proj') // cwd still from the head
      expect(meta.title).toBe('Parser rewrite') // title from the tail
      expect(meta.titleSource).toBe('customTitle')
    })

    it('drops the trailing partial line when the file extends past 16KB', async () => {
      // First line carries the cwd; a giant second line straddles the
      // 16KB boundary and must be discarded, not parsed.
      const file = path.join(dir, 'head-partial.jsonl')
      await fs.writeFile(file, jsonl([
        userEntry('short opener', { cwd: '/Users/x/proj' }),
        userEntry('w'.repeat(64 * 1024)),
        assistantEntry('far past the window'),
      ]))
      const meta = await readSessionHeadMeta(file)
      expect(meta.cwd).toBe('/Users/x/proj')
    })

    it('never throws — missing file returns cwd null', async () => {
      const meta = await readSessionHeadMeta(path.join(dir, 'nope.jsonl'))
      expect(meta.cwd).toBeNull()
      expect(meta.title).toBeUndefined()
    })

    it('never throws — corrupt content returns cwd null', async () => {
      const file = path.join(dir, 'head-corrupt.jsonl')
      await fs.writeFile(file, 'garbage\nmore garbage\n')
      const meta = await readSessionHeadMeta(file)
      expect(meta.cwd).toBeNull()
    })
  })
})
